version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"